1) 
    ```bash
    AttributeError at /admin/userauths/profile/add/
    'Profile' object has no attribute 'profile_pic'
    Request Method:	POST
    Request URL:	http://127.0.0.1:8000/admin/userauths/profile/add/
    Django Version:	5.1.4
    Exception Type:	AttributeError
    Exception Value:	
    'Profile' object has no attribute 'profile_pic'
    Exception Location:	/Users/sandeepthati/Documents/GitHub/LMS_React_Django/learning-management-platform-React-Django/backend/backend/userauths/models.py, line 43, in save
    Raised during:	django.contrib.admin.options.add_view
    Python Executable:	/Users/sandeepthati/Documents/GitHub/LMS_React_Django/learning-management-platform-React-Django/backend/venv/bin/python3
    Python Version:	3.11.4
    Python Path:	
    ['/Users/sandeepthati/Documents/GitHub/LMS_React_Django/learning-management-platform-React-Django/backend/backend',
    '/Library/Frameworks/Python.framework/Versions/3.11/lib/python311.zip',
    '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11',
    '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload',
    '/Users/sandeepthati/Documents/GitHub/LMS_React_Django/learning-management-platform-React-Django/backend/venv/lib/python3.11/site-packages']
    Server time:	Sat, 11 Jan 2025 22:53:49 +0000
    ```